using System.Text;

namespace XamlToCSharpGenerator.Avalonia.Emission;

public sealed partial class AvaloniaCodeEmitter
{
    private static void EmitPreamble(EmitContext context, StringBuilder sourceBuilder)
    {
        var viewModel = context.ViewModel;
        sourceBuilder.AppendLine("// <auto-generated />");
        if (viewModel.PassExecutionTrace.Length > 0)
        {
            foreach (var traceEntry in viewModel.PassExecutionTrace)
            {
                sourceBuilder.AppendLine("// pass: " + CSharpLiteralEmissionService.NormalizeCommentText(traceEntry));
            }
        }

        sourceBuilder.AppendLine("#nullable enable annotations");
        sourceBuilder.AppendLine("#nullable disable warnings");
        sourceBuilder.AppendLine("using global::Avalonia.Controls;");
        sourceBuilder.AppendLine("using global::Avalonia.Markup.Xaml;");
        sourceBuilder.AppendLine("using global::System.Runtime.CompilerServices;");
        sourceBuilder.AppendLine("using __AXSGObjectGraph = global::XamlToCSharpGenerator.Runtime.SourceGenObjectGraphRuntimeHelpers;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"namespace {context.NamespaceName}");
        sourceBuilder.AppendLine("{");
    }

    private static void EmitTypeOpening(EmitContext context, StringBuilder sourceBuilder)
    {
        var viewModel = context.ViewModel;
        var classKeyword = viewModel.Document.IsClassBacked ? "partial class" : "static class";
        sourceBuilder.AppendLine($"    {viewModel.ClassModifier} {classKeyword} {context.ClassName}");
        sourceBuilder.AppendLine("    {");

        if (viewModel.Document.IsClassBacked)
        {
            foreach (var namedElement in viewModel.NamedElements)
            {
                var fieldName = context.NamedFieldMap.TryGetValue(namedElement.Name, out var mappedFieldName)
                    ? mappedFieldName
                    : IdentifierSanitizationService.SanitizeIdentifier(namedElement.Name);
                sourceBuilder.AppendLine(
                    $"        {namedElement.FieldModifier} {namedElement.TypeName} {fieldName} = null!;");
            }

            if (viewModel.HasXBind)
            {
                sourceBuilder.AppendLine("        private __SourceGenXBindBindings? __sourceGenBindings;");
                sourceBuilder.AppendLine("        public __SourceGenXBindBindings Bindings => __sourceGenBindings ??= new __SourceGenXBindBindings(this);");
            }
        }

        sourceBuilder.AppendLine($"        private const string __SourceGenDocumentUri = \"{context.EscapedUri}\";");
        sourceBuilder.AppendLine(
            $"        private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, string> __BindingXmlNamespaces = {context.BindingXmlNamespaceMapExpression};");
        sourceBuilder.AppendLine();
    }
}
