using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using XamlToCSharpGenerator.Core.Abstractions;
using XamlToCSharpGenerator.Core.Models;

namespace XamlToCSharpGenerator.Avalonia.Emission;

public sealed class AvaloniaCodeEmitter : IXamlCodeEmitter
{
    private const string TopDownAttachValueToken = "__AXSG_VALUE__";
    private const string MarkupContextServiceProviderToken = "__AXSG_CTX_SERVICE_PROVIDER__";
    private const string MarkupContextRootObjectToken = "__AXSG_CTX_ROOT_OBJECT__";
    private const string MarkupContextIntermediateRootObjectToken = "__AXSG_CTX_INTERMEDIATE_ROOT_OBJECT__";
    private const string MarkupContextTargetObjectToken = "__AXSG_CTX_TARGET_OBJECT__";
    private const string MarkupContextTargetPropertyToken = "__AXSG_CTX_TARGET_PROPERTY__";
    private const string MarkupContextBaseUriToken = "__AXSG_CTX_BASE_URI__";
    private const string MarkupContextParentStackToken = "__AXSG_CTX_PARENT_STACK__";

    private static readonly IReadOnlyDictionary<string, string> EmptyNamedFieldMap =
        new Dictionary<string, string>(StringComparer.Ordinal);

    public (string HintName, string Source) Emit(ResolvedViewModel viewModel)
    {
        var document = viewModel.Document;
        var namespaceName = document.ClassNamespace;
        var className = document.ClassName;
        var escapedUri = Escape(viewModel.BuildUri);
        var emitHotReloadStateTracking = viewModel.Document.IsClassBacked && viewModel.EnableHotReload;
        var namedFieldMap = BuildNamedFieldMap(viewModel);
        var hotReloadCollectionMembers = ImmutableArray<string>.Empty;
        var hotReloadClrPropertyMembers = ImmutableArray<string>.Empty;
        var hotReloadAvaloniaPropertyMembers = ImmutableArray<string>.Empty;
        var hotReloadRootEventSubscriptions = ImmutableArray<ResolvedEventSubscription>.Empty;
        var hotReloadClearsRootCollection = false;

        if (emitHotReloadStateTracking)
        {
            hotReloadCollectionMembers = BuildRootHotReloadCollectionMembers(viewModel.RootObject);
            hotReloadClrPropertyMembers = BuildRootHotReloadClrPropertyMembers(viewModel.RootObject, namedFieldMap);
            hotReloadAvaloniaPropertyMembers = BuildRootHotReloadAvaloniaPropertyMembers(viewModel.RootObject);
            hotReloadRootEventSubscriptions = BuildRootHotReloadEventSubscriptions(viewModel.RootObject);
            hotReloadClearsRootCollection = ShouldClearRootSelfCollection(viewModel.RootObject);
        }

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated />");
        if (viewModel.PassExecutionTrace.Length > 0)
        {
            foreach (var traceEntry in viewModel.PassExecutionTrace)
            {
                sourceBuilder.AppendLine("// pass: " + EscapeComment(traceEntry));
            }
        }
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine("using global::Avalonia.Controls;");
        sourceBuilder.AppendLine("using global::Avalonia.Markup.Xaml;");
        sourceBuilder.AppendLine("using global::System.Runtime.CompilerServices;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"namespace {namespaceName}");
        sourceBuilder.AppendLine("{");
        var classKeyword = viewModel.Document.IsClassBacked ? "partial class" : "static class";
        sourceBuilder.AppendLine($"    {viewModel.ClassModifier} {classKeyword} {className}");
        sourceBuilder.AppendLine("    {");

        if (viewModel.Document.IsClassBacked)
        {
            foreach (var namedElement in viewModel.NamedElements)
            {
                sourceBuilder.AppendLine($"        {namedElement.FieldModifier} {namedElement.TypeName}? {SanitizeIdentifier(namedElement.Name)};");
            }
        }

        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        [ModuleInitializer]");
        sourceBuilder.AppendLine("        internal static void __RegisterXamlSourceGenArtifacts()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlSourceGenRegistry.Unregister(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlSourceInfoRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlResourceRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlTemplateRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlStyleRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlControlThemeRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlIncludeRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlIncludeGraphRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlCompiledBindingRegistry.Clear(\"{escapedUri}\");");
        sourceBuilder.AppendLine($"            global::XamlToCSharpGenerator.Runtime.XamlSourceGenRegistry.Register(\"{escapedUri}\", static __serviceProvider =>");
        sourceBuilder.AppendLine("            {");
            sourceBuilder.AppendLine("                var __instance = __CreateRootInstance(__serviceProvider);");
            sourceBuilder.AppendLine("                __PopulateGeneratedObjectGraph(__instance, __serviceProvider);");
            sourceBuilder.AppendLine("                return __instance;");
        sourceBuilder.AppendLine("            });");

        if (viewModel.CreateSourceInfo)
        {
            EmitSourceInfoRegistrations(viewModel, sourceBuilder, escapedUri);
        }

        foreach (var resource in viewModel.Resources)
        {
            sourceBuilder.AppendLine(
                $"            global::XamlToCSharpGenerator.Runtime.XamlResourceRegistry.Register(\"{escapedUri}\", \"{Escape(resource.Key)}\", \"{Escape(resource.TypeName)}\", \"{Escape(resource.RawXaml)}\");");
        }

        foreach (var template in viewModel.Templates)
        {
            sourceBuilder.AppendLine(
                $"            global::XamlToCSharpGenerator.Runtime.XamlTemplateRegistry.Register(\"{escapedUri}\", \"{Escape(template.Kind)}\", {ToQuotedOrNull(template.Key)}, {ToQuotedOrNull(template.TargetTypeName)}, {ToQuotedOrNull(template.DataType)}, \"{Escape(template.RawXaml)}\");");
        }

        foreach (var style in viewModel.Styles)
        {
            sourceBuilder.AppendLine(
                $"            global::XamlToCSharpGenerator.Runtime.XamlStyleRegistry.Register(\"{escapedUri}\", {ToQuotedOrNull(style.Key)}, \"{Escape(style.Selector)}\", {ToQuotedOrNull(style.TargetTypeName)}, \"{Escape(style.RawXaml)}\");");
        }

        for (var controlThemeIndex = 0; controlThemeIndex < viewModel.ControlThemes.Length; controlThemeIndex++)
        {
            var controlTheme = viewModel.ControlThemes[controlThemeIndex];
            sourceBuilder.AppendLine(
                $"            global::XamlToCSharpGenerator.Runtime.XamlControlThemeRegistry.Register(\"{escapedUri}\", {ToQuotedOrNull(controlTheme.Key)}, {ToQuotedOrNull(controlTheme.TargetTypeName)}, {ToQuotedOrNull(controlTheme.BasedOn)}, {ToQuotedOrNull(controlTheme.ThemeVariant)}, \"{Escape(controlTheme.RawXaml)}\", static () => __BuildGeneratedControlTheme{controlThemeIndex}());");
        }

        foreach (var include in viewModel.Includes)
        {
            sourceBuilder.AppendLine(
                $"            global::XamlToCSharpGenerator.Runtime.XamlIncludeRegistry.Register(\"{escapedUri}\", \"{Escape(include.Kind)}\", \"{Escape(include.Source)}\", \"{Escape(include.MergeTarget)}\", {BoolLiteral(include.IsAbsoluteUri)}, \"{Escape(include.RawXaml)}\");");

            if (!string.IsNullOrWhiteSpace(include.ResolvedSourceUri) && include.IsProjectLocal)
            {
                sourceBuilder.AppendLine(
                    $"            global::XamlToCSharpGenerator.Runtime.XamlIncludeGraphRegistry.Register(\"{escapedUri}\", \"{Escape(include.ResolvedSourceUri!)}\", \"{Escape(include.MergeTarget)}\");");
            }
        }

        for (var index = 0; index < viewModel.CompiledBindings.Length; index++)
        {
            var compiledBinding = viewModel.CompiledBindings[index];
            sourceBuilder.AppendLine(
                $"            global::XamlToCSharpGenerator.Runtime.XamlCompiledBindingRegistry.Register(\"{escapedUri}\", \"{Escape(compiledBinding.TargetTypeName)}\", \"{Escape(compiledBinding.TargetPropertyName)}\", \"{Escape(compiledBinding.Path)}\", \"{Escape(compiledBinding.SourceTypeName)}\", static source => __CompiledBindingAccessor{index}(({compiledBinding.SourceTypeName})source));");
        }

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine(
            $"        internal static void __PopulateGeneratedObjectGraph({viewModel.RootObject.TypeName} __root, global::System.IServiceProvider? __serviceProvider = null)");
        sourceBuilder.AppendLine("        {");
        if (viewModel.EmitNameScopeRegistration)
        {
            sourceBuilder.AppendLine("            var __nameScope = new global::Avalonia.Controls.NameScope();");
            sourceBuilder.AppendLine("            if (__root is global::Avalonia.StyledElement __rootStyledElement)");
            sourceBuilder.AppendLine("            {");
            sourceBuilder.AppendLine("                global::Avalonia.Controls.NameScope.SetNameScope(__rootStyledElement, __nameScope);");
            sourceBuilder.AppendLine("            }");
        }

        var nodeCounter = 0;
        EmitNode(
            viewModel.RootObject,
            sourceBuilder,
            ref nodeCounter,
            "            ",
            "__root",
            namedFieldMap,
            viewModel.EmitNameScopeRegistration,
            viewModel.EmitNameScopeRegistration ? "__nameScope" : null,
            "__root",
            topDownAttachmentTemplate: null,
            completeNameScopeOnNodeCompletion: viewModel.EmitNameScopeRegistration,
            serviceProviderReference: "__serviceProvider",
            baseUriExpression: "\"" + escapedUri + "\"",
            parentStackReferences: ImmutableArray<string>.Empty,
            intermediateRootReference: "__root");

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine(
            $"        internal static {viewModel.RootObject.TypeName} __CreateRootInstance(global::System.IServiceProvider? __serviceProvider)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine($"            return {BuildObjectCreationExpression(viewModel.RootObject, "__serviceProvider")};");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"        internal static {viewModel.RootObject.TypeName} __BuildGeneratedObjectGraph()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            var __root = __CreateRootInstance(null);");
        sourceBuilder.AppendLine("            __PopulateGeneratedObjectGraph(__root, null);");
        sourceBuilder.AppendLine("            return __root;");

        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        if (viewModel.Document.IsClassBacked && viewModel.EnableHotReload)
        {
            sourceBuilder.AppendLine("        private static string[] __GetSourceGenHotReloadCollectionMembers()");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine($"            return {BuildStringArrayExpression(hotReloadCollectionMembers)};");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("        private static string[] __GetSourceGenHotReloadClrPropertyMembers()");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine($"            return {BuildStringArrayExpression(hotReloadClrPropertyMembers)};");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("        private static string[] __GetSourceGenHotReloadAvaloniaPropertyMembers()");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine($"            return {BuildStringArrayExpression(hotReloadAvaloniaPropertyMembers)};");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine(
                "        private static global::XamlToCSharpGenerator.Runtime.SourceGenHotReloadEventDescriptor[] __GetSourceGenHotReloadRootEventSubscriptions()");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine(
                $"            return {BuildHotReloadEventDescriptorArrayExpression(hotReloadRootEventSubscriptions)};");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("        private static void __TrackAndReconcileSourceGenHotReloadState(object __instance)");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine("            global::XamlToCSharpGenerator.Runtime.XamlSourceGenHotReloadStateTracker.Reconcile(");
            sourceBuilder.AppendLine("                __instance,");
            sourceBuilder.AppendLine("                __GetSourceGenHotReloadCollectionMembers(),");
            sourceBuilder.AppendLine("                __GetSourceGenHotReloadClrPropertyMembers(),");
            sourceBuilder.AppendLine("                __GetSourceGenHotReloadAvaloniaPropertyMembers(),");
            sourceBuilder.AppendLine($"                {BoolLiteral(hotReloadClearsRootCollection)},");
            sourceBuilder.AppendLine("                __GetSourceGenHotReloadRootEventSubscriptions());");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("        internal void __ApplySourceGenHotReload()");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine("            __RegisterXamlSourceGenArtifacts();");
            sourceBuilder.AppendLine("            __TrackAndReconcileSourceGenHotReloadState(this);");
            sourceBuilder.AppendLine("            __PopulateGeneratedObjectGraph(this, null);");
            sourceBuilder.AppendLine("            var __self = (object)this;");
            sourceBuilder.AppendLine("            if (__self is global::Avalonia.Layout.Layoutable __layoutable)");
            sourceBuilder.AppendLine("            {");
            sourceBuilder.AppendLine("                __layoutable.InvalidateMeasure();");
            sourceBuilder.AppendLine("                __layoutable.InvalidateArrange();");
            sourceBuilder.AppendLine("            }");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("            if (__self is global::Avalonia.Visual __visual)");
            sourceBuilder.AppendLine("            {");
            sourceBuilder.AppendLine("                __visual.InvalidateVisual();");
            sourceBuilder.AppendLine("            }");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
        }

        if (viewModel.CompiledBindings.Length > 0)
        {
            sourceBuilder.AppendLine();
        }

        for (var index = 0; index < viewModel.CompiledBindings.Length; index++)
        {
            var compiledBinding = viewModel.CompiledBindings[index];
            sourceBuilder.AppendLine($"        private static object? __CompiledBindingAccessor{index}({compiledBinding.SourceTypeName} source)");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine($"            return {compiledBinding.AccessorExpression};");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
        }

        for (var themeIndex = 0; themeIndex < viewModel.ControlThemes.Length; themeIndex++)
        {
            var controlTheme = viewModel.ControlThemes[themeIndex];
            sourceBuilder.AppendLine(
                $"        private static global::Avalonia.Styling.ControlTheme __BuildGeneratedControlTheme{themeIndex}()");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine("            var __theme = new global::Avalonia.Styling.ControlTheme();");

            if (!string.IsNullOrWhiteSpace(controlTheme.TargetTypeName))
            {
                sourceBuilder.AppendLine(
                    $"            __theme.TargetType = typeof({controlTheme.TargetTypeName});");
            }

            for (var setterIndex = 0; setterIndex < controlTheme.Setters.Length; setterIndex++)
            {
                var setter = controlTheme.Setters[setterIndex];
                if (string.IsNullOrWhiteSpace(setter.AvaloniaPropertyOwnerTypeName) ||
                    string.IsNullOrWhiteSpace(setter.AvaloniaPropertyFieldName))
                {
                    continue;
                }

                sourceBuilder.AppendLine(
                    $"            __theme.Setters.Add(new global::Avalonia.Styling.Setter({setter.AvaloniaPropertyOwnerTypeName}.{setter.AvaloniaPropertyFieldName}, {setter.ValueExpression}));");
            }

            sourceBuilder.AppendLine("            return __theme;");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
        }

        if (viewModel.EmitStaticResourceResolver)
        {
            sourceBuilder.AppendLine("        private static object? __ResolveStaticResource(object? anchor, object key)");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine(
                $"            return global::XamlToCSharpGenerator.Runtime.SourceGenStaticResourceResolver.Resolve(anchor, key, \"{escapedUri}\");");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine();
        }

        sourceBuilder.AppendLine("        private static void __TryClearCollection(object? value)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            switch (value)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                case null:");
        sourceBuilder.AppendLine("                    return;");
        sourceBuilder.AppendLine("                case global::Avalonia.Controls.IResourceDictionary resourceDictionary:");
        sourceBuilder.AppendLine("                    try");
        sourceBuilder.AppendLine("                    {");
        sourceBuilder.AppendLine("                        resourceDictionary.Clear();");
        sourceBuilder.AppendLine("                    }");
        sourceBuilder.AppendLine("                    catch (global::System.NotSupportedException)");
        sourceBuilder.AppendLine("                    {");
        sourceBuilder.AppendLine("                    }");
        sourceBuilder.AppendLine("                    __TryClearCollection(resourceDictionary.MergedDictionaries);");
        sourceBuilder.AppendLine("                    __TryClearCollection(resourceDictionary.ThemeDictionaries);");
        sourceBuilder.AppendLine("                    return;");
        sourceBuilder.AppendLine("                case global::System.Collections.IDictionary dictionary:");
        sourceBuilder.AppendLine("                    try");
        sourceBuilder.AppendLine("                    {");
        sourceBuilder.AppendLine("                        dictionary.Clear();");
        sourceBuilder.AppendLine("                    }");
        sourceBuilder.AppendLine("                    catch (global::System.NotSupportedException)");
        sourceBuilder.AppendLine("                    {");
        sourceBuilder.AppendLine("                    }");
        sourceBuilder.AppendLine("                    return;");
        sourceBuilder.AppendLine("                case global::System.Collections.IList list:");
        sourceBuilder.AppendLine("                    try");
        sourceBuilder.AppendLine("                    {");
        sourceBuilder.AppendLine("                        if (list.IsReadOnly || list.IsFixedSize)");
        sourceBuilder.AppendLine("                        {");
        sourceBuilder.AppendLine("                            return;");
        sourceBuilder.AppendLine("                        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("                        list.Clear();");
        sourceBuilder.AppendLine("                    }");
        sourceBuilder.AppendLine("                    catch (global::System.InvalidOperationException)");
        sourceBuilder.AppendLine("                    {");
        sourceBuilder.AppendLine("                    }");
        sourceBuilder.AppendLine("                    catch (global::System.NotSupportedException)");
        sourceBuilder.AppendLine("                    {");
        sourceBuilder.AppendLine("                    }");
        sourceBuilder.AppendLine("                    return;");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("            __TryInvokeClearMethod(value);");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        private static void __TryInvokeClearMethod(object? value)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            if (value is null)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                return;");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("            var __type = value.GetType();");
        sourceBuilder.AppendLine("            var __methods = __type.GetMethods(global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic);");
        sourceBuilder.AppendLine("            for (var __index = 0; __index < __methods.Length; __index++)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                var __method = __methods[__index];");
        sourceBuilder.AppendLine("                if (!string.Equals(__method.Name, \"Clear\", global::System.StringComparison.Ordinal) ||");
        sourceBuilder.AppendLine("                    __method.IsStatic ||");
        sourceBuilder.AppendLine("                    __method.IsAbstract ||");
        sourceBuilder.AppendLine("                    __method.ReturnType != typeof(void) ||");
        sourceBuilder.AppendLine("                    __method.GetParameters().Length != 0)");
        sourceBuilder.AppendLine("                {");
        sourceBuilder.AppendLine("                    continue;");
        sourceBuilder.AppendLine("                }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("                try");
        sourceBuilder.AppendLine("                {");
        sourceBuilder.AppendLine("                    __method.Invoke(value, null);");
        sourceBuilder.AppendLine("                }");
        sourceBuilder.AppendLine("                catch");
        sourceBuilder.AppendLine("                {");
        sourceBuilder.AppendLine("                }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("                return;");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        private static void __TryMergeDictionary(object? destination, object? source)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            if (destination is not global::System.Collections.IDictionary destinationDictionary ||");
        sourceBuilder.AppendLine("                source is not global::System.Collections.IDictionary sourceDictionary)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                return;");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("            foreach (global::System.Collections.DictionaryEntry entry in sourceDictionary)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                destinationDictionary[entry.Key] = entry.Value;");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        private static void __BeginInit(object? value)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            if (value is global::System.ComponentModel.ISupportInitialize initialize)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                initialize.BeginInit();");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        private static void __EndInit(object? value)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            if (value is global::System.ComponentModel.ISupportInitialize initialize)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                initialize.EndInit();");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        private static void __TryCompleteNameScope(object? scope)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            if (scope is global::Avalonia.Controls.INameScope nameScope && !nameScope.IsCompleted)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                nameScope.Complete();");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        if (viewModel.Document.IsClassBacked)
        {
            sourceBuilder.AppendLine("        public void InitializeComponent(bool loadXaml = true)");
            sourceBuilder.AppendLine("            {");
            sourceBuilder.AppendLine("                var __loadedWithSourceGen = false;");
            sourceBuilder.AppendLine("                if (loadXaml)");
            sourceBuilder.AppendLine("                {");
            sourceBuilder.AppendLine("                    __PopulateGeneratedObjectGraph(this, null);");
            sourceBuilder.AppendLine("                    __loadedWithSourceGen = true;");
            sourceBuilder.AppendLine("                }");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("                if (!__loadedWithSourceGen)");
            sourceBuilder.AppendLine("                {");
            foreach (var namedElement in viewModel.NamedElements)
            {
                sourceBuilder.AppendLine(
                    $"                    {SanitizeIdentifier(namedElement.Name)} = this.FindNameScope()?.Find<{namedElement.TypeName}>(\"{Escape(namedElement.Name)}\");");
            }
            sourceBuilder.AppendLine("                }");
            sourceBuilder.AppendLine();
            if (viewModel.EnableHotReload)
            {
                var escapedSourcePath = Escape(viewModel.Document.FilePath);
                sourceBuilder.AppendLine("                if (__loadedWithSourceGen)");
                sourceBuilder.AppendLine("                {");
                sourceBuilder.AppendLine("                    __TrackAndReconcileSourceGenHotReloadState(this);");
                sourceBuilder.AppendLine(
                    $"                    global::XamlToCSharpGenerator.Runtime.XamlSourceGenHotReloadManager.Register(this, static __instance => (({viewModel.RootObject.TypeName})__instance).__ApplySourceGenHotReload(), new global::XamlToCSharpGenerator.Runtime.SourceGenHotReloadRegistrationOptions");
                sourceBuilder.AppendLine("                    {");
                sourceBuilder.AppendLine($"                        SourcePath = \"{escapedSourcePath}\",");
                sourceBuilder.AppendLine("                        CaptureState = static __instance =>");
                sourceBuilder.AppendLine("                            __instance is global::Avalonia.StyledElement __styledElement");
                sourceBuilder.AppendLine("                                ? __styledElement.DataContext");
                sourceBuilder.AppendLine("                                : null,");
                sourceBuilder.AppendLine("                        RestoreState = static (__instance, __state) =>");
                sourceBuilder.AppendLine("                        {");
                sourceBuilder.AppendLine("                            if (__instance is global::Avalonia.StyledElement __styledElement &&");
                sourceBuilder.AppendLine("                                __styledElement.DataContext is null)");
                sourceBuilder.AppendLine("                            {");
                sourceBuilder.AppendLine("                                __styledElement.DataContext = __state;");
                sourceBuilder.AppendLine("                            }");
                sourceBuilder.AppendLine("                        }");
                sourceBuilder.AppendLine("                    });");
                sourceBuilder.AppendLine("                }");
            }

            sourceBuilder.AppendLine("            }");
        }
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine("}");

        var hintName = BuildHintName(viewModel);
        return (hintName, sourceBuilder.ToString());
    }

    private static string EmitNode(
        ResolvedObjectNode node,
        StringBuilder sourceBuilder,
        ref int nodeCounter,
        string indent,
        string rootReference,
        IReadOnlyDictionary<string, string> namedFieldMap,
        bool emitNameScopeRegistration,
        string? nameScopeReference,
        string? existingVariableName = null,
        string? topDownAttachmentTemplate = null,
        bool completeNameScopeOnNodeCompletion = false,
        string serviceProviderReference = "__serviceProvider",
        string baseUriExpression = "null",
        ImmutableArray<string> parentStackReferences = default,
        string? intermediateRootReference = null)
    {
        var variableName = existingVariableName ?? ("__n" + nodeCounter.ToString());
        intermediateRootReference ??= variableName;
        var nodeParentStackReferences = ExtendParentStack(parentStackReferences, variableName);
        var nodeParentStackExpression = BuildParentStackExpression(nodeParentStackReferences);

        if (TryEmitDeferredTemplateNode(
                node,
                sourceBuilder,
                ref nodeCounter,
                indent,
                rootReference,
                variableName,
                namedFieldMap,
                emitNameScopeRegistration,
                nameScopeReference,
                existingVariableName is null,
                topDownAttachmentTemplate,
                completeNameScopeOnNodeCompletion,
                serviceProviderReference,
                baseUriExpression,
                nodeParentStackReferences,
                intermediateRootReference))
        {
            return variableName;
        }

        if (existingVariableName is null)
        {
            nodeCounter++;
            sourceBuilder.AppendLine($"{indent}var {variableName} = {BuildObjectCreationExpression(node, serviceProviderReference)};");
        }

        sourceBuilder.AppendLine($"{indent}__BeginInit({variableName});");
        if (node.UseTopDownInitialization &&
            !string.IsNullOrWhiteSpace(topDownAttachmentTemplate))
        {
            sourceBuilder.AppendLine($"{indent}{ExpandTopDownAttachmentTemplate(topDownAttachmentTemplate!, variableName)}");
        }

        if (!string.IsNullOrWhiteSpace(node.Name))
        {
            if (namedFieldMap.TryGetValue(node.Name!, out var fieldName))
            {
                sourceBuilder.AppendLine($"{indent}{rootReference}.{fieldName} = {variableName};");
            }

            if (emitNameScopeRegistration &&
                !string.IsNullOrWhiteSpace(nameScopeReference))
            {
                sourceBuilder.AppendLine(
                    $"{indent}{nameScopeReference}.Register(\"{Escape(node.Name!)}\", {variableName});");
            }
        }

        foreach (var assignment in node.PropertyAssignments)
        {
            var targetPropertyExpression = BuildTargetPropertyExpression(assignment);
            var valueExpression = ExpandMarkupContextExpression(
                assignment.ValueExpression,
                serviceProviderReference,
                rootReference,
                intermediateRootReference,
                variableName,
                targetPropertyExpression,
                baseUriExpression,
                nodeParentStackExpression);

            if (string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyFieldName))
            {
                sourceBuilder.AppendLine($"{indent}{variableName}.{assignment.PropertyName} = {valueExpression};");
            }
            else
            {
                if (LooksLikeBindingExpression(valueExpression))
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}[new global::Avalonia.Data.IndexerDescriptor {{ Property = {assignment.AvaloniaPropertyOwnerTypeName}.{assignment.AvaloniaPropertyFieldName} }}] = {valueExpression};");
                    continue;
                }

                if (string.IsNullOrWhiteSpace(assignment.BindingPriorityExpression))
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({assignment.AvaloniaPropertyOwnerTypeName}.{assignment.AvaloniaPropertyFieldName}, {valueExpression});");
                }
                else
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({assignment.AvaloniaPropertyOwnerTypeName}.{assignment.AvaloniaPropertyFieldName}, {valueExpression}, {assignment.BindingPriorityExpression});");
                }
            }
        }

        foreach (var eventSubscription in node.EventSubscriptions)
        {
            EmitEventSubscription(
                sourceBuilder,
                indent,
                variableName,
                rootReference,
                eventSubscription);
        }

        foreach (var propertyElementAssignment in node.PropertyElementAssignments)
        {
            if (propertyElementAssignment.IsCollectionAdd)
            {
                sourceBuilder.AppendLine($"{indent}__TryClearCollection({variableName}.{propertyElementAssignment.PropertyName});");
                foreach (var value in propertyElementAssignment.ObjectValues)
                {
                    var inlineAddTemplate = $"{variableName}.{propertyElementAssignment.PropertyName}.Add({TopDownAttachValueToken});";
                    var valueVariable = EmitNode(
                        value,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference: serviceProviderReference,
                        topDownAttachmentTemplate: inlineAddTemplate,
                        baseUriExpression: baseUriExpression,
                        parentStackReferences: nodeParentStackReferences,
                        intermediateRootReference: intermediateRootReference);
                    if (!value.UseTopDownInitialization)
                    {
                        sourceBuilder.AppendLine($"{indent}{variableName}.{propertyElementAssignment.PropertyName}.Add({valueVariable});");
                    }
                }

                continue;
            }

            if (propertyElementAssignment.IsDictionaryMerge)
            {
                if (TryEmitDictionaryMergePropertyElement(
                        propertyElementAssignment,
                        variableName,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference,
                        baseUriExpression,
                        nodeParentStackReferences,
                        intermediateRootReference))
                {
                    continue;
                }
            }

            if (propertyElementAssignment.ObjectValues.Length == 0)
            {
                continue;
            }

            string assignmentTemplate;
            if (string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyFieldName))
            {
                assignmentTemplate = $"{variableName}.{propertyElementAssignment.PropertyName} = {TopDownAttachValueToken};";
            }
            else if (string.IsNullOrWhiteSpace(propertyElementAssignment.BindingPriorityExpression))
            {
                assignmentTemplate =
                    $"{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {TopDownAttachValueToken});";
            }
            else
            {
                assignmentTemplate =
                    $"{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {TopDownAttachValueToken}, {propertyElementAssignment.BindingPriorityExpression});";
            }

            var assignedNode = propertyElementAssignment.ObjectValues[0];
            var assignedValue = EmitNode(
                assignedNode,
                sourceBuilder,
                ref nodeCounter,
                indent,
                rootReference,
                namedFieldMap,
                emitNameScopeRegistration,
                nameScopeReference,
                serviceProviderReference: serviceProviderReference,
                topDownAttachmentTemplate: assignmentTemplate,
                baseUriExpression: baseUriExpression,
                parentStackReferences: nodeParentStackReferences,
                intermediateRootReference: intermediateRootReference);
            if (assignedNode.UseTopDownInitialization)
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyFieldName))
            {
                sourceBuilder.AppendLine($"{indent}{variableName}.{propertyElementAssignment.PropertyName} = {assignedValue};");
            }
            else
            {
                if (string.IsNullOrWhiteSpace(propertyElementAssignment.BindingPriorityExpression))
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {assignedValue});");
                }
                else
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {assignedValue}, {propertyElementAssignment.BindingPriorityExpression});");
                }
            }
        }

        switch (node.ChildAttachmentMode)
        {
            case ResolvedChildAttachmentMode.Content:
            {
                var contentPropertyName = string.IsNullOrWhiteSpace(node.ContentPropertyName)
                    ? "Content"
                    : node.ContentPropertyName!;
                var shouldResetImplicitContent =
                    existingVariableName is not null &&
                    string.IsNullOrWhiteSpace(topDownAttachmentTemplate);
                if (node.Children.Length > 0)
                {
                    var firstChildNode = node.Children[0];
                    var firstChild = EmitNode(
                        firstChildNode,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference: serviceProviderReference,
                        topDownAttachmentTemplate: $"{variableName}.{contentPropertyName} = {TopDownAttachValueToken};",
                        baseUriExpression: baseUriExpression,
                        parentStackReferences: nodeParentStackReferences,
                        intermediateRootReference: intermediateRootReference);
                    if (!firstChildNode.UseTopDownInitialization)
                    {
                        sourceBuilder.AppendLine($"{indent}{variableName}.{contentPropertyName} = {firstChild};");
                    }
                }
                else if (shouldResetImplicitContent && !HasExplicitContentValue(node, contentPropertyName))
                {
                    sourceBuilder.AppendLine($"{indent}{variableName}.{contentPropertyName} = default!;");
                }

                break;
            }
            case ResolvedChildAttachmentMode.ChildrenCollection:
            {
                sourceBuilder.AppendLine($"{indent}__TryClearCollection({variableName}.Children);");
                foreach (var child in node.Children)
                {
                    var inlineAddTemplate = $"{variableName}.Children.Add({TopDownAttachValueToken});";
                    var childVariable = EmitNode(
                        child,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference: serviceProviderReference,
                        topDownAttachmentTemplate: inlineAddTemplate,
                        baseUriExpression: baseUriExpression,
                        parentStackReferences: nodeParentStackReferences,
                        intermediateRootReference: intermediateRootReference);
                    if (!child.UseTopDownInitialization)
                    {
                        sourceBuilder.AppendLine($"{indent}{variableName}.Children.Add({childVariable});");
                    }
                }

                break;
            }
            case ResolvedChildAttachmentMode.ItemsCollection:
            {
                sourceBuilder.AppendLine($"{indent}__TryClearCollection({variableName}.Items);");
                foreach (var child in node.Children)
                {
                    var inlineAddTemplate = $"{variableName}.Items.Add({TopDownAttachValueToken});";
                    var childVariable = EmitNode(
                        child,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference: serviceProviderReference,
                        topDownAttachmentTemplate: inlineAddTemplate,
                        baseUriExpression: baseUriExpression,
                        parentStackReferences: nodeParentStackReferences,
                        intermediateRootReference: intermediateRootReference);
                    if (!child.UseTopDownInitialization)
                    {
                        sourceBuilder.AppendLine($"{indent}{variableName}.Items.Add({childVariable});");
                    }
                }

                break;
            }
            case ResolvedChildAttachmentMode.DirectAdd:
            {
                sourceBuilder.AppendLine($"{indent}__TryClearCollection({variableName});");
                foreach (var child in node.Children)
                {
                    var inlineAddTemplate = $"{variableName}.Add({TopDownAttachValueToken});";
                    var childVariable = EmitNode(
                        child,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference: serviceProviderReference,
                        topDownAttachmentTemplate: inlineAddTemplate,
                        baseUriExpression: baseUriExpression,
                        parentStackReferences: nodeParentStackReferences,
                        intermediateRootReference: intermediateRootReference);
                    if (!child.UseTopDownInitialization)
                    {
                        sourceBuilder.AppendLine($"{indent}{variableName}.Add({childVariable});");
                    }
                }

                break;
            }
            case ResolvedChildAttachmentMode.DictionaryAdd:
            {
                sourceBuilder.AppendLine($"{indent}__TryClearCollection({variableName});");
                foreach (var child in node.Children)
                {
                    if (string.IsNullOrWhiteSpace(child.KeyExpression))
                    {
                        continue;
                    }

                    var childVariable = EmitNode(
                        child,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference: serviceProviderReference,
                        topDownAttachmentTemplate: $"{variableName}.Add({child.KeyExpression}, {TopDownAttachValueToken});",
                        baseUriExpression: baseUriExpression,
                        parentStackReferences: nodeParentStackReferences,
                        intermediateRootReference: intermediateRootReference);
                    if (!child.UseTopDownInitialization)
                    {
                        sourceBuilder.AppendLine($"{indent}{variableName}.Add({child.KeyExpression}, {childVariable});");
                    }
                }

                break;
            }
        }

        if (completeNameScopeOnNodeCompletion &&
            !string.IsNullOrWhiteSpace(nameScopeReference))
        {
            sourceBuilder.AppendLine($"{indent}__TryCompleteNameScope({nameScopeReference});");
        }

        sourceBuilder.AppendLine($"{indent}__EndInit({variableName});");
        return variableName;
    }

    private static bool TryEmitDeferredTemplateNode(
        ResolvedObjectNode node,
        StringBuilder sourceBuilder,
        ref int nodeCounter,
        string indent,
        string rootReference,
        string variableName,
        IReadOnlyDictionary<string, string> namedFieldMap,
        bool emitNameScopeRegistration,
        string? nameScopeReference,
        bool shouldCreateVariable,
        string? topDownAttachmentTemplate,
        bool completeNameScopeOnNodeCompletion,
        string serviceProviderReference,
        string baseUriExpression,
        ImmutableArray<string> parentStackReferences,
        string intermediateRootReference)
    {
        if (!IsDeferredTemplateNode(node))
        {
            return false;
        }

        var nodeParentStackReferences = ExtendParentStack(parentStackReferences, variableName);
        var nodeParentStackExpression = BuildParentStackExpression(nodeParentStackReferences);

        if (shouldCreateVariable)
        {
            nodeCounter++;
            sourceBuilder.AppendLine($"{indent}var {variableName} = {BuildObjectCreationExpression(node, serviceProviderReference)};");
        }

        sourceBuilder.AppendLine($"{indent}__BeginInit({variableName});");
        if (node.UseTopDownInitialization &&
            !string.IsNullOrWhiteSpace(topDownAttachmentTemplate))
        {
            sourceBuilder.AppendLine($"{indent}{ExpandTopDownAttachmentTemplate(topDownAttachmentTemplate!, variableName)}");
        }

        if (!string.IsNullOrWhiteSpace(node.Name))
        {
            if (namedFieldMap.TryGetValue(node.Name!, out var fieldName))
            {
                sourceBuilder.AppendLine($"{indent}{rootReference}.{fieldName} = {variableName};");
            }

            if (emitNameScopeRegistration &&
                !string.IsNullOrWhiteSpace(nameScopeReference))
            {
                sourceBuilder.AppendLine(
                    $"{indent}{nameScopeReference}.Register(\"{Escape(node.Name!)}\", {variableName});");
            }
        }

        foreach (var assignment in node.PropertyAssignments)
        {
            if (IsContentPropertyName(assignment.PropertyName))
            {
                continue;
            }

            var targetPropertyExpression = BuildTargetPropertyExpression(assignment);
            var valueExpression = ExpandMarkupContextExpression(
                assignment.ValueExpression,
                serviceProviderReference,
                rootReference,
                intermediateRootReference,
                variableName,
                targetPropertyExpression,
                baseUriExpression,
                nodeParentStackExpression);

            if (string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyFieldName))
            {
                sourceBuilder.AppendLine($"{indent}{variableName}.{assignment.PropertyName} = {valueExpression};");
            }
            else
            {
                if (LooksLikeBindingExpression(valueExpression))
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}[new global::Avalonia.Data.IndexerDescriptor {{ Property = {assignment.AvaloniaPropertyOwnerTypeName}.{assignment.AvaloniaPropertyFieldName} }}] = {valueExpression};");
                    continue;
                }

                if (string.IsNullOrWhiteSpace(assignment.BindingPriorityExpression))
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({assignment.AvaloniaPropertyOwnerTypeName}.{assignment.AvaloniaPropertyFieldName}, {valueExpression});");
                }
                else
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({assignment.AvaloniaPropertyOwnerTypeName}.{assignment.AvaloniaPropertyFieldName}, {valueExpression}, {assignment.BindingPriorityExpression});");
                }
            }
        }

        foreach (var eventSubscription in node.EventSubscriptions)
        {
            EmitEventSubscription(
                sourceBuilder,
                indent,
                variableName,
                rootReference,
                eventSubscription);
        }

        foreach (var propertyElementAssignment in node.PropertyElementAssignments)
        {
            if (IsContentPropertyName(propertyElementAssignment.PropertyName))
            {
                continue;
            }

            if (propertyElementAssignment.IsCollectionAdd)
            {
                sourceBuilder.AppendLine($"{indent}__TryClearCollection({variableName}.{propertyElementAssignment.PropertyName});");
                foreach (var value in propertyElementAssignment.ObjectValues)
                {
                    var inlineAddTemplate = $"{variableName}.{propertyElementAssignment.PropertyName}.Add({TopDownAttachValueToken});";
                    var valueVariable = EmitNode(
                        value,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference: serviceProviderReference,
                        topDownAttachmentTemplate: inlineAddTemplate,
                        baseUriExpression: baseUriExpression,
                        parentStackReferences: nodeParentStackReferences,
                        intermediateRootReference: intermediateRootReference);
                    if (!value.UseTopDownInitialization)
                    {
                        sourceBuilder.AppendLine($"{indent}{variableName}.{propertyElementAssignment.PropertyName}.Add({valueVariable});");
                    }
                }

                continue;
            }

            if (propertyElementAssignment.IsDictionaryMerge)
            {
                if (TryEmitDictionaryMergePropertyElement(
                        propertyElementAssignment,
                        variableName,
                        sourceBuilder,
                        ref nodeCounter,
                        indent,
                        rootReference,
                        namedFieldMap,
                        emitNameScopeRegistration,
                        nameScopeReference,
                        serviceProviderReference,
                        baseUriExpression,
                        nodeParentStackReferences,
                        intermediateRootReference))
                {
                    continue;
                }
            }

            if (propertyElementAssignment.ObjectValues.Length == 0)
            {
                continue;
            }

            string assignmentTemplate;
            if (string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyFieldName))
            {
                assignmentTemplate = $"{variableName}.{propertyElementAssignment.PropertyName} = {TopDownAttachValueToken};";
            }
            else if (string.IsNullOrWhiteSpace(propertyElementAssignment.BindingPriorityExpression))
            {
                assignmentTemplate =
                    $"{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {TopDownAttachValueToken});";
            }
            else
            {
                assignmentTemplate =
                    $"{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {TopDownAttachValueToken}, {propertyElementAssignment.BindingPriorityExpression});";
            }

            var assignedNode = propertyElementAssignment.ObjectValues[0];
            var assignedValue = EmitNode(
                assignedNode,
                sourceBuilder,
                ref nodeCounter,
                indent,
                rootReference,
                namedFieldMap,
                emitNameScopeRegistration,
                nameScopeReference,
                serviceProviderReference: serviceProviderReference,
                topDownAttachmentTemplate: assignmentTemplate,
                baseUriExpression: baseUriExpression,
                parentStackReferences: nodeParentStackReferences,
                intermediateRootReference: intermediateRootReference);
            if (assignedNode.UseTopDownInitialization)
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(propertyElementAssignment.AvaloniaPropertyFieldName))
            {
                sourceBuilder.AppendLine($"{indent}{variableName}.{propertyElementAssignment.PropertyName} = {assignedValue};");
            }
            else
            {
                if (string.IsNullOrWhiteSpace(propertyElementAssignment.BindingPriorityExpression))
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {assignedValue});");
                }
                else
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.SetValue({propertyElementAssignment.AvaloniaPropertyOwnerTypeName}.{propertyElementAssignment.AvaloniaPropertyFieldName}, {assignedValue}, {propertyElementAssignment.BindingPriorityExpression});");
                }
            }
        }

        var contentNode = TryGetTemplateContentNode(node);
        var templateContentPropertyName = string.IsNullOrWhiteSpace(node.ContentPropertyName)
            ? "Content"
            : node.ContentPropertyName!;
        if (contentNode is not null)
        {
            var factoryIndent = indent + "    ";
            var templateScopeName = "__templateScope" + nodeCounter.ToString();
            var templateProviderName = "__templateProvider" + nodeCounter.ToString();
            sourceBuilder.AppendLine(
                $"{indent}{variableName}.{templateContentPropertyName} = (global::System.Func<global::System.IServiceProvider?, object?>)(__templateServiceProvider =>");
            sourceBuilder.AppendLine($"{indent}{{");
            sourceBuilder.AppendLine(
                $"{factoryIndent}var {templateScopeName} = global::XamlToCSharpGenerator.Runtime.SourceGenDeferredServiceProviderFactory.CreateTemplateNameScope(__templateServiceProvider);");
            sourceBuilder.AppendLine(
                $"{factoryIndent}var {templateProviderName} = global::XamlToCSharpGenerator.Runtime.SourceGenDeferredServiceProviderFactory.CreateDeferredTemplateServiceProvider(__templateServiceProvider, {rootReference}, {templateScopeName});");
            var templateRoot = EmitNode(
                contentNode,
                sourceBuilder,
                ref nodeCounter,
                factoryIndent,
                rootReference,
                EmptyNamedFieldMap,
                emitNameScopeRegistration: true,
                nameScopeReference: templateScopeName,
                completeNameScopeOnNodeCompletion: true,
                serviceProviderReference: templateProviderName,
                baseUriExpression: baseUriExpression,
                parentStackReferences: nodeParentStackReferences,
                intermediateRootReference: variableName);
            sourceBuilder.AppendLine($"{factoryIndent}if ({templateRoot} is global::Avalonia.StyledElement __templateStyledElement)");
            sourceBuilder.AppendLine($"{factoryIndent}{{");
            sourceBuilder.AppendLine(
                $"{factoryIndent}    global::Avalonia.Controls.NameScope.SetNameScope(__templateStyledElement, {templateScopeName});");
            sourceBuilder.AppendLine($"{factoryIndent}}}");
            sourceBuilder.AppendLine(
                $"{factoryIndent}return new global::Avalonia.Controls.Templates.TemplateResult<global::Avalonia.Controls.Control>((global::Avalonia.Controls.Control){templateRoot}, {templateScopeName});");
            sourceBuilder.AppendLine($"{indent}}});");
        }

        if (completeNameScopeOnNodeCompletion &&
            !string.IsNullOrWhiteSpace(nameScopeReference))
        {
            sourceBuilder.AppendLine($"{indent}__TryCompleteNameScope({nameScopeReference});");
        }

        sourceBuilder.AppendLine($"{indent}__EndInit({variableName});");
        return true;
    }

    private static void EmitEventSubscription(
        StringBuilder sourceBuilder,
        string indent,
        string variableName,
        string rootReference,
        ResolvedEventSubscription eventSubscription)
    {
        if (eventSubscription.Kind == ResolvedEventSubscriptionKind.RoutedEvent &&
            !string.IsNullOrWhiteSpace(eventSubscription.RoutedEventOwnerTypeName) &&
            !string.IsNullOrWhiteSpace(eventSubscription.RoutedEventFieldName))
        {
            var routedEventReference = eventSubscription.RoutedEventOwnerTypeName + "." + eventSubscription.RoutedEventFieldName;
            var handlerExpression = string.IsNullOrWhiteSpace(eventSubscription.RoutedEventHandlerTypeName)
                ? rootReference + "." + eventSubscription.HandlerMethodName
                : "(" + eventSubscription.RoutedEventHandlerTypeName + ")" + rootReference + "." + eventSubscription.HandlerMethodName;
            sourceBuilder.AppendLine(
                $"{indent}{variableName}.RemoveHandler({routedEventReference}, {handlerExpression});");
            sourceBuilder.AppendLine(
                $"{indent}{variableName}.AddHandler({routedEventReference}, {handlerExpression});");
            return;
        }

        sourceBuilder.AppendLine(
            $"{indent}{variableName}.{eventSubscription.EventName} -= {rootReference}.{eventSubscription.HandlerMethodName};");
        sourceBuilder.AppendLine(
            $"{indent}{variableName}.{eventSubscription.EventName} += {rootReference}.{eventSubscription.HandlerMethodName};");
    }

    private static bool TryEmitDictionaryMergePropertyElement(
        ResolvedPropertyElementAssignment propertyElementAssignment,
        string variableName,
        StringBuilder sourceBuilder,
        ref int nodeCounter,
        string indent,
        string rootReference,
        IReadOnlyDictionary<string, string> namedFieldMap,
        bool emitNameScopeRegistration,
        string? nameScopeReference,
        string serviceProviderReference,
        string baseUriExpression,
        ImmutableArray<string> parentStackReferences,
        string intermediateRootReference)
    {
        sourceBuilder.AppendLine($"{indent}__TryClearCollection({variableName}.{propertyElementAssignment.PropertyName});");

        if (propertyElementAssignment.ObjectValues.Length == 0)
        {
            return true;
        }

        var hasKeyedObjectValues = true;
        foreach (var objectValue in propertyElementAssignment.ObjectValues)
        {
            if (string.IsNullOrWhiteSpace(objectValue.KeyExpression))
            {
                hasKeyedObjectValues = false;
                break;
            }
        }

        if (hasKeyedObjectValues)
        {
            foreach (var keyedObjectValue in propertyElementAssignment.ObjectValues)
            {
                var keyedChildVariable = EmitNode(
                    keyedObjectValue,
                    sourceBuilder,
                    ref nodeCounter,
                    indent,
                    rootReference,
                    namedFieldMap,
                    emitNameScopeRegistration,
                    nameScopeReference,
                    serviceProviderReference: serviceProviderReference,
                    topDownAttachmentTemplate: $"{variableName}.{propertyElementAssignment.PropertyName}.Add({keyedObjectValue.KeyExpression}, {TopDownAttachValueToken});",
                    baseUriExpression: baseUriExpression,
                    parentStackReferences: parentStackReferences,
                    intermediateRootReference: intermediateRootReference);
                if (!keyedObjectValue.UseTopDownInitialization)
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.{propertyElementAssignment.PropertyName}.Add({keyedObjectValue.KeyExpression}, {keyedChildVariable});");
                }
            }

            return true;
        }

        var valueNode = propertyElementAssignment.ObjectValues[0];
        if (valueNode.ChildAttachmentMode == ResolvedChildAttachmentMode.DictionaryAdd)
        {
            foreach (var child in valueNode.Children)
            {
                if (string.IsNullOrWhiteSpace(child.KeyExpression))
                {
                    continue;
                }

                var childVariable = EmitNode(
                    child,
                    sourceBuilder,
                    ref nodeCounter,
                    indent,
                    rootReference,
                    namedFieldMap,
                    emitNameScopeRegistration,
                    nameScopeReference,
                    serviceProviderReference: serviceProviderReference,
                    topDownAttachmentTemplate: $"{variableName}.{propertyElementAssignment.PropertyName}.Add({child.KeyExpression}, {TopDownAttachValueToken});",
                    baseUriExpression: baseUriExpression,
                    parentStackReferences: parentStackReferences,
                    intermediateRootReference: intermediateRootReference);
                if (!child.UseTopDownInitialization)
                {
                    sourceBuilder.AppendLine(
                        $"{indent}{variableName}.{propertyElementAssignment.PropertyName}.Add({child.KeyExpression}, {childVariable});");
                }
            }

            return true;
        }

        var assignedValue = EmitNode(
            valueNode,
            sourceBuilder,
            ref nodeCounter,
            indent,
            rootReference,
            namedFieldMap,
            emitNameScopeRegistration,
            nameScopeReference,
            serviceProviderReference: serviceProviderReference,
            baseUriExpression: baseUriExpression,
            parentStackReferences: parentStackReferences,
            intermediateRootReference: intermediateRootReference);
        sourceBuilder.AppendLine(
            $"{indent}__TryMergeDictionary({variableName}.{propertyElementAssignment.PropertyName}, {assignedValue});");
        return true;
    }

    private static ResolvedObjectNode? TryGetTemplateContentNode(ResolvedObjectNode node)
    {
        foreach (var assignment in node.PropertyElementAssignments)
        {
            if (IsContentPropertyName(assignment.PropertyName) &&
                assignment.ObjectValues.Length > 0)
            {
                return assignment.ObjectValues[0];
            }
        }

        if (node.Children.Length > 0)
        {
            return node.Children[0];
        }

        return null;
    }

    private static bool IsDeferredTemplateNode(ResolvedObjectNode node)
    {
        return node.TypeName is "global::Avalonia.Markup.Xaml.Templates.Template"
            or "global::Avalonia.Markup.Xaml.Templates.DataTemplate"
            or "global::Avalonia.Markup.Xaml.Templates.TreeDataTemplate"
            or "global::Avalonia.Markup.Xaml.Templates.ControlTemplate"
            or "global::Avalonia.Markup.Xaml.Templates.FocusAdornerTemplate"
            or "global::Avalonia.Markup.Xaml.Templates.ItemsPanelTemplate";
    }

    private static IReadOnlyDictionary<string, string> BuildNamedFieldMap(ResolvedViewModel viewModel)
    {
        if (!viewModel.Document.IsClassBacked)
        {
            return new Dictionary<string, string>(StringComparer.Ordinal);
        }

        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var namedElement in viewModel.NamedElements)
        {
            map[namedElement.Name] = SanitizeIdentifier(namedElement.Name);
        }

        return map;
    }

    private static ImmutableArray<string> ExtendParentStack(ImmutableArray<string> parentStackReferences, string currentReference)
    {
        if (!parentStackReferences.IsDefaultOrEmpty &&
            parentStackReferences[0].Equals(currentReference, StringComparison.Ordinal))
        {
            return parentStackReferences;
        }

        var builder = ImmutableArray.CreateBuilder<string>(parentStackReferences.Length + 1);
        builder.Add(currentReference);
        if (!parentStackReferences.IsDefaultOrEmpty)
        {
            builder.AddRange(parentStackReferences);
        }

        return builder.ToImmutable();
    }

    private static string BuildParentStackExpression(ImmutableArray<string> parentStackReferences)
    {
        if (parentStackReferences.IsDefaultOrEmpty)
        {
            return "global::System.Array.Empty<object>()";
        }

        return "new object[] { " + string.Join(", ", parentStackReferences) + " }";
    }

    private static string ExpandMarkupContextExpression(
        string valueExpression,
        string serviceProviderReference,
        string rootReference,
        string intermediateRootReference,
        string targetObjectReference,
        string targetPropertyExpression,
        string baseUriExpression,
        string parentStackExpression)
    {
        var expanded = valueExpression
            .Replace(MarkupContextServiceProviderToken, serviceProviderReference, StringComparison.Ordinal)
            .Replace(MarkupContextRootObjectToken, rootReference, StringComparison.Ordinal)
            .Replace(MarkupContextIntermediateRootObjectToken, intermediateRootReference, StringComparison.Ordinal)
            .Replace(MarkupContextTargetObjectToken, targetObjectReference, StringComparison.Ordinal)
            .Replace(MarkupContextTargetPropertyToken, targetPropertyExpression, StringComparison.Ordinal)
            .Replace(MarkupContextBaseUriToken, baseUriExpression, StringComparison.Ordinal)
            .Replace(MarkupContextParentStackToken, parentStackExpression, StringComparison.Ordinal);

        return expanded;
    }

    private static string BuildObjectCreationExpression(ResolvedObjectNode node, string serviceProviderReference)
    {
        if (!string.IsNullOrWhiteSpace(node.FactoryExpression))
        {
            return node.FactoryExpression!;
        }

        return node.UseServiceProviderConstructor
            ? "new " + node.TypeName + "(global::XamlToCSharpGenerator.Runtime.SourceGenServiceProviderUtilities.EnsureNotNull(" + serviceProviderReference + "))"
            : "new " + node.TypeName + "()";
    }

    private static string ExpandTopDownAttachmentTemplate(string template, string valueExpression)
    {
        return template.Replace(TopDownAttachValueToken, valueExpression, StringComparison.Ordinal);
    }

    private static void EmitSourceInfoRegistrations(ResolvedViewModel viewModel, StringBuilder sourceBuilder, string escapedUri)
    {
        var document = viewModel.Document;
        var escapedFilePath = Escape(document.FilePath);
        EmitSourceInfoRegistration(
            sourceBuilder,
            escapedUri,
            escapedFilePath,
            "Root",
            document.ClassFullName ?? document.ClassName,
            document.RootObject.Line,
            document.RootObject.Column);

        EmitObjectSourceInfoRegistrations(
            viewModel.RootObject,
            sourceBuilder,
            escapedUri,
            escapedFilePath,
            "Object:0");

        for (var index = 0; index < viewModel.NamedElements.Length; index++)
        {
            var namedElement = viewModel.NamedElements[index];
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "NamedElement",
                BuildIndexedIdentity("NamedElement", index, namedElement.Name),
                namedElement.Line,
                namedElement.Column);
        }

        for (var index = 0; index < viewModel.Resources.Length; index++)
        {
            var resource = viewModel.Resources[index];
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "Resource",
                BuildIndexedIdentity("Resource", index, resource.Key),
                resource.Line,
                resource.Column);
        }

        for (var index = 0; index < viewModel.Templates.Length; index++)
        {
            var template = viewModel.Templates[index];
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "Template",
                BuildIndexedIdentity("Template", index, (template.Key ?? string.Empty) + "|" + template.Kind),
                template.Line,
                template.Column);
        }

        for (var styleIndex = 0; styleIndex < viewModel.Styles.Length; styleIndex++)
        {
            var style = viewModel.Styles[styleIndex];
            var styleIdentity = BuildIndexedIdentity("Style", styleIndex, style.Selector);
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "Style",
                styleIdentity,
                style.Line,
                style.Column);

            for (var setterIndex = 0; setterIndex < style.Setters.Length; setterIndex++)
            {
                var setter = style.Setters[setterIndex];
                EmitSourceInfoRegistration(
                    sourceBuilder,
                    escapedUri,
                    escapedFilePath,
                    "StyleSetter",
                    styleIdentity + "/Setter:" + setterIndex.ToString() + ":" + setter.PropertyName,
                    setter.Line,
                    setter.Column);
            }
        }

        for (var themeIndex = 0; themeIndex < viewModel.ControlThemes.Length; themeIndex++)
        {
            var controlTheme = viewModel.ControlThemes[themeIndex];
            var themeIdentity = BuildIndexedIdentity("ControlTheme", themeIndex, controlTheme.Key);
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "ControlTheme",
                themeIdentity,
                controlTheme.Line,
                controlTheme.Column);

            for (var setterIndex = 0; setterIndex < controlTheme.Setters.Length; setterIndex++)
            {
                var setter = controlTheme.Setters[setterIndex];
                EmitSourceInfoRegistration(
                    sourceBuilder,
                    escapedUri,
                    escapedFilePath,
                    "ControlThemeSetter",
                    themeIdentity + "/Setter:" + setterIndex.ToString() + ":" + setter.PropertyName,
                    setter.Line,
                    setter.Column);
            }
        }

        for (var index = 0; index < viewModel.Includes.Length; index++)
        {
            var include = viewModel.Includes[index];
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "Include",
                BuildIndexedIdentity("Include", index, include.Source + "|" + include.MergeTarget),
                include.Line,
                include.Column);
        }

        for (var index = 0; index < viewModel.CompiledBindings.Length; index++)
        {
            var binding = viewModel.CompiledBindings[index];
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "CompiledBinding",
                BuildIndexedIdentity("CompiledBinding", index, binding.TargetPropertyName + "|" + binding.Path),
                binding.Line,
                binding.Column);
        }
    }

    private static void EmitObjectSourceInfoRegistrations(
        ResolvedObjectNode node,
        StringBuilder sourceBuilder,
        string escapedUri,
        string escapedFilePath,
        string objectIdentity)
    {
        EmitSourceInfoRegistration(
            sourceBuilder,
            escapedUri,
            escapedFilePath,
            "Object",
            objectIdentity + ":" + node.TypeName,
            node.Line,
            node.Column);

        for (var assignmentIndex = 0; assignmentIndex < node.PropertyAssignments.Length; assignmentIndex++)
        {
            var assignment = node.PropertyAssignments[assignmentIndex];
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "Property",
                objectIdentity + "/Property:" + assignmentIndex.ToString() + ":" + assignment.PropertyName,
                assignment.Line,
                assignment.Column);
        }

        for (var eventIndex = 0; eventIndex < node.EventSubscriptions.Length; eventIndex++)
        {
            var eventSubscription = node.EventSubscriptions[eventIndex];
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "Event",
                objectIdentity + "/Event:" + eventIndex.ToString() + ":" + eventSubscription.EventName,
                eventSubscription.Line,
                eventSubscription.Column);
        }

        for (var assignmentIndex = 0; assignmentIndex < node.PropertyElementAssignments.Length; assignmentIndex++)
        {
            var propertyElement = node.PropertyElementAssignments[assignmentIndex];
            var propertyElementIdentity = objectIdentity + "/PropertyElement:" + assignmentIndex.ToString() + ":" +
                                          propertyElement.PropertyName;
            EmitSourceInfoRegistration(
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                "PropertyElement",
                propertyElementIdentity,
                propertyElement.Line,
                propertyElement.Column);

            for (var valueIndex = 0; valueIndex < propertyElement.ObjectValues.Length; valueIndex++)
            {
                EmitObjectSourceInfoRegistrations(
                    propertyElement.ObjectValues[valueIndex],
                    sourceBuilder,
                    escapedUri,
                    escapedFilePath,
                    propertyElementIdentity + "/Value:" + valueIndex.ToString());
            }
        }

        for (var childIndex = 0; childIndex < node.Children.Length; childIndex++)
        {
            EmitObjectSourceInfoRegistrations(
                node.Children[childIndex],
                sourceBuilder,
                escapedUri,
                escapedFilePath,
                objectIdentity + "/Child:" + childIndex.ToString());
        }
    }

    private static void EmitSourceInfoRegistration(
        StringBuilder sourceBuilder,
        string escapedUri,
        string escapedFilePath,
        string kind,
        string identity,
        int line,
        int column)
    {
        sourceBuilder.AppendLine(
            $"            global::XamlToCSharpGenerator.Runtime.XamlSourceInfoRegistry.Register(\"{escapedUri}\", \"{Escape(kind)}\", \"{Escape(identity)}\", \"{escapedFilePath}\", {line}, {column});");
    }

    private static string BuildIndexedIdentity(string kind, int index, string? hint)
    {
        var normalizedHint = string.IsNullOrWhiteSpace(hint) ? "<none>" : hint!;
        return kind + ":" + index.ToString() + ":" + normalizedHint;
    }

    private static string ToQuotedOrNull(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "null";
        }

        return "\"" + Escape(value!) + "\"";
    }

    private static string BoolLiteral(bool value)
    {
        return value ? "true" : "false";
    }

    private static string BuildStringArrayExpression(ImmutableArray<string> values)
    {
        if (values.IsDefaultOrEmpty)
        {
            return "global::System.Array.Empty<string>()";
        }

        var builder = new StringBuilder();
        builder.Append("new string[] { ");
        for (var index = 0; index < values.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append('"');
            builder.Append(Escape(values[index]));
            builder.Append('"');
        }

        builder.Append(" }");
        return builder.ToString();
    }

    private static ImmutableArray<string> BuildRootHotReloadCollectionMembers(ResolvedObjectNode rootNode)
    {
        var members = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var assignment in rootNode.PropertyElementAssignments)
        {
            if (!assignment.IsCollectionAdd && !assignment.IsDictionaryMerge)
            {
                continue;
            }

            var memberName = ExtractMemberName(assignment.PropertyName);
            if (!string.IsNullOrWhiteSpace(memberName))
            {
                members.Add(memberName);
            }
        }

        switch (rootNode.ChildAttachmentMode)
        {
            case ResolvedChildAttachmentMode.ChildrenCollection:
                members.Add("Children");
                break;
            case ResolvedChildAttachmentMode.ItemsCollection:
                members.Add("Items");
                break;
        }

        return ToImmutableArray(members);
    }

    private static ImmutableArray<string> BuildRootHotReloadClrPropertyMembers(
        ResolvedObjectNode rootNode,
        IReadOnlyDictionary<string, string> namedFieldMap)
    {
        var members = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var assignment in rootNode.PropertyAssignments)
        {
            if (!string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyOwnerTypeName) &&
                !string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyFieldName))
            {
                continue;
            }

            var memberName = ExtractMemberName(assignment.PropertyName);
            if (!string.IsNullOrWhiteSpace(memberName))
            {
                members.Add(memberName);
            }
        }

        foreach (var assignment in rootNode.PropertyElementAssignments)
        {
            if (assignment.IsCollectionAdd ||
                assignment.IsDictionaryMerge ||
                assignment.ObjectValues.Length == 0)
            {
                continue;
            }

            if (!string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyOwnerTypeName) &&
                !string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyFieldName))
            {
                continue;
            }

            var memberName = ExtractMemberName(assignment.PropertyName);
            if (!string.IsNullOrWhiteSpace(memberName))
            {
                members.Add(memberName);
            }
        }

        foreach (var fieldName in namedFieldMap.Values)
        {
            if (!string.IsNullOrWhiteSpace(fieldName))
            {
                members.Add(fieldName);
            }
        }

        return ToImmutableArray(members);
    }

    private static ImmutableArray<string> BuildRootHotReloadAvaloniaPropertyMembers(ResolvedObjectNode rootNode)
    {
        var members = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var assignment in rootNode.PropertyAssignments)
        {
            if (string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyFieldName))
            {
                continue;
            }

            members.Add(assignment.AvaloniaPropertyOwnerTypeName + "." + assignment.AvaloniaPropertyFieldName);
        }

        foreach (var assignment in rootNode.PropertyElementAssignments)
        {
            if (assignment.IsCollectionAdd ||
                assignment.IsDictionaryMerge ||
                assignment.ObjectValues.Length == 0 ||
                string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyOwnerTypeName) ||
                string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyFieldName))
            {
                continue;
            }

            members.Add(assignment.AvaloniaPropertyOwnerTypeName + "." + assignment.AvaloniaPropertyFieldName);
        }

        return ToImmutableArray(members);
    }

    private static ImmutableArray<ResolvedEventSubscription> BuildRootHotReloadEventSubscriptions(ResolvedObjectNode rootNode)
    {
        if (rootNode.EventSubscriptions.IsDefaultOrEmpty)
        {
            return ImmutableArray<ResolvedEventSubscription>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<ResolvedEventSubscription>(rootNode.EventSubscriptions.Length);
        foreach (var eventSubscription in rootNode.EventSubscriptions)
        {
            if (string.IsNullOrWhiteSpace(eventSubscription.HandlerMethodName))
            {
                continue;
            }

            if (eventSubscription.Kind == ResolvedEventSubscriptionKind.ClrEvent &&
                string.IsNullOrWhiteSpace(eventSubscription.EventName))
            {
                continue;
            }

            if (eventSubscription.Kind == ResolvedEventSubscriptionKind.RoutedEvent &&
                (string.IsNullOrWhiteSpace(eventSubscription.RoutedEventOwnerTypeName) ||
                 string.IsNullOrWhiteSpace(eventSubscription.RoutedEventFieldName) ||
                 string.IsNullOrWhiteSpace(eventSubscription.RoutedEventHandlerTypeName)))
            {
                continue;
            }

            builder.Add(eventSubscription);
        }

        return builder.Count == 0
            ? ImmutableArray<ResolvedEventSubscription>.Empty
            : builder.ToImmutable();
    }

    private static bool ShouldClearRootSelfCollection(ResolvedObjectNode rootNode)
    {
        return rootNode.ChildAttachmentMode is ResolvedChildAttachmentMode.DirectAdd or ResolvedChildAttachmentMode.DictionaryAdd;
    }

    private static string ExtractMemberName(string propertyName)
    {
        if (string.IsNullOrWhiteSpace(propertyName))
        {
            return string.Empty;
        }

        var separatorIndex = propertyName.LastIndexOf('.');
        if (separatorIndex < 0 || separatorIndex >= propertyName.Length - 1)
        {
            return propertyName;
        }

        return propertyName.Substring(separatorIndex + 1);
    }

    private static ImmutableArray<string> ToImmutableArray(SortedSet<string> values)
    {
        if (values.Count == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>(values.Count);
        foreach (var value in values)
        {
            builder.Add(value);
        }

        return builder.ToImmutable();
    }

    private static string BuildHotReloadEventDescriptorArrayExpression(ImmutableArray<ResolvedEventSubscription> eventSubscriptions)
    {
        if (eventSubscriptions.IsDefaultOrEmpty)
        {
            return "global::System.Array.Empty<global::XamlToCSharpGenerator.Runtime.SourceGenHotReloadEventDescriptor>()";
        }

        var builder = new StringBuilder();
        builder.Append("new global::XamlToCSharpGenerator.Runtime.SourceGenHotReloadEventDescriptor[] { ");
        for (var index = 0; index < eventSubscriptions.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            var eventSubscription = eventSubscriptions[index];
            builder.Append("new global::XamlToCSharpGenerator.Runtime.SourceGenHotReloadEventDescriptor(");
            builder.Append('"').Append(Escape(eventSubscription.EventName ?? string.Empty)).Append('"').Append(", ");
            builder.Append('"').Append(Escape(eventSubscription.HandlerMethodName)).Append('"').Append(", ");
            builder.Append(BoolLiteral(eventSubscription.Kind == ResolvedEventSubscriptionKind.RoutedEvent)).Append(", ");
            builder.Append(ToQuotedOrNull(eventSubscription.RoutedEventOwnerTypeName)).Append(", ");
            builder.Append(ToQuotedOrNull(eventSubscription.RoutedEventFieldName)).Append(", ");
            builder.Append(ToQuotedOrNull(eventSubscription.RoutedEventHandlerTypeName));
            builder.Append(")");
        }

        builder.Append(" }");
        return builder.ToString();
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", string.Empty)
            .Replace("\n", "\\n");
    }

    private static string EscapeComment(string value)
    {
        return value.Replace("\r", " ").Replace("\n", " ");
    }

    private static string SanitizeIdentifier(string identifier)
    {
        if (string.IsNullOrWhiteSpace(identifier))
        {
            return "UnnamedElement";
        }

        var chars = identifier.ToCharArray();
        for (var index = 0; index < chars.Length; index++)
        {
            if (!char.IsLetterOrDigit(chars[index]) && chars[index] != '_')
            {
                chars[index] = '_';
            }
        }

        if (!char.IsLetter(chars[0]) && chars[0] != '_')
        {
            return "_" + new string(chars);
        }

        return new string(chars);
    }

    private static string BuildTargetPropertyExpression(ResolvedPropertyAssignment assignment)
    {
        if (!string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyOwnerTypeName) &&
            !string.IsNullOrWhiteSpace(assignment.AvaloniaPropertyFieldName))
        {
            return assignment.AvaloniaPropertyOwnerTypeName + "." + assignment.AvaloniaPropertyFieldName;
        }

        if (!string.IsNullOrWhiteSpace(assignment.ClrPropertyOwnerTypeName) &&
            !string.IsNullOrWhiteSpace(assignment.ClrPropertyTypeName))
        {
            return
                "global::XamlToCSharpGenerator.Runtime.SourceGenProvideValueTargetPropertyFactory.CreateWritable<" +
                assignment.ClrPropertyOwnerTypeName +
                ", " +
                assignment.ClrPropertyTypeName +
                ">(\"" +
                Escape(assignment.PropertyName) +
                "\", static (__target, __value) => __target." +
                assignment.PropertyName +
                " = __value)";
        }

        return "null";
    }

    private static bool LooksLikeBindingExpression(string valueExpression)
    {
        return valueExpression.StartsWith("new global::Avalonia.Data.Binding(", StringComparison.Ordinal) ||
               valueExpression.StartsWith("new Avalonia.Data.Binding(", StringComparison.Ordinal) ||
               valueExpression.StartsWith("new Binding(", StringComparison.Ordinal) ||
               valueExpression.Contains(
                   "SourceGenMarkupExtensionRuntime.ProvideReflectionBinding(",
                   StringComparison.Ordinal) ||
               valueExpression.Contains(
                   "SourceGenMarkupExtensionRuntime.ProvideDynamicResource(",
                   StringComparison.Ordinal);
    }

    private static bool HasExplicitContentValue(ResolvedObjectNode node, string contentPropertyName)
    {
        foreach (var assignment in node.PropertyAssignments)
        {
            if (IsContentPropertyName(assignment.PropertyName, contentPropertyName))
            {
                return true;
            }
        }

        foreach (var assignment in node.PropertyElementAssignments)
        {
            if (IsContentPropertyName(assignment.PropertyName, contentPropertyName))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsContentPropertyName(string propertyName, string contentPropertyName = "Content")
    {
        if (propertyName.Equals(contentPropertyName, StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var separatorIndex = propertyName.LastIndexOf('.');
        if (separatorIndex >= 0 &&
            separatorIndex < propertyName.Length - 1)
        {
            return propertyName.Substring(separatorIndex + 1)
                .Equals(contentPropertyName, StringComparison.OrdinalIgnoreCase);
        }

        return false;
    }

    private static string BuildHintName(ResolvedViewModel viewModel)
    {
        var sourceIdentity = viewModel.BuildUri;
        if (string.IsNullOrWhiteSpace(sourceIdentity))
        {
            sourceIdentity = (viewModel.Document.ClassFullName ?? viewModel.Document.ClassName) + "|" + viewModel.Document.TargetPath;
        }

        var hash = ComputeStableHashHex(sourceIdentity);
        var baseName = viewModel.Document.ClassFullName ?? (viewModel.Document.ClassNamespace + "." + viewModel.Document.ClassName);
        var sanitizedBaseName = SanitizeHintSegment(baseName);
        return sanitizedBaseName + "." + hash + ".XamlSourceGen.g.cs";
    }

    private static string SanitizeHintSegment(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "GeneratedXaml";
        }

        var chars = value.ToCharArray();
        for (var index = 0; index < chars.Length; index++)
        {
            var c = chars[index];
            if (!char.IsLetterOrDigit(c) && c != '_' && c != '.')
            {
                chars[index] = '_';
            }
        }

        return new string(chars);
    }

    private static string ComputeStableHashHex(string text)
    {
        unchecked
        {
            var hash = 2166136261u;
            foreach (var c in text)
            {
                hash ^= c;
                hash *= 16777619u;
            }

            return hash.ToString("x8");
        }
    }
}
